### ISSUE TITLE
Suggestion: Alignment paremeter

### ISSUE THREAD

**Issue by torrobinson** [NotNotWrongUsually/OutConsolePicture#4]
This is amazing, I was looking for a module to exactly this, so thank you!

I have a feature suggestion - an `Align` parameter would be great.

- Left is what it does by default currently
- Right could make the image hug the right of the buffer
- Center could get the current buffer width, and if the generated ansi width is smaller than the buffer, divide the empty space in half and render empty space before each line, to effectively "center" the image in the buffer.

**Comment by NotNotWrongUsually** [comment]
Good suggestion. I've just added a HorizontalPositioning parameter in the positioning branch. Will get transparency sorted out too later and update the module.

**Comment by torrobinson** [comment]
Thanks! By the way, I implemented both in #6 a year ago and have been running with that ever since (I wanted some silly transparent logos in my PS profile lol)
